arch: resnet50
name: random
dataset: nova
dataset_location: /scratch_nvme/jakobj/multimag
batch_size: 64
workers: 2
epochs: 150
lr: 0.001
lr_schedule: exponential
lr_gamma: 0.97
weight_decay: 1.0e-5
gpus: [0, 1]
