arch: resnet18
name: random
dataset: cifar
dataset_location: /scratch/jakobj/cifar
batch_size: 1024
workers: 4
lr_schedule: cosine-anneal
epochs: 1000
lr: 1.
weight_decay: 1.0e-4
tau: 1.
multiplier: 2
seed: -1
gpus: [3]