arch: resnet50
name: random
chkpt_file: ./cifar.pth
dataset: cifar
dataset_location: /scratch/jakobj/cifar
batch_size: 1024
workers: 2
lr_schedule: "exponential"
lr_gamma: 0.99
epochs: 100
lr: 0.01
weight_decay: 1.0e-6
find_unused_parameters: False
seed: -1
gpus: [0, 1, 2, 3]
optimizer: "adam"
port: "1235"