arch: resnet18
name: random
dataset: cifar
dataset_location: /scratch/jakobj/cifar
batch_size: 1024
workers: 4
lr_schedule: cosine-anneal
epochs: 150
lr: 0.1
weight_decay: 1.0e-4
seed: -1
gpus: [0, 1]