arch: resnet50
name: random
dataset: cifar
dataset_location: /scratch/jakobj/cifar
batch_size: 512
workers: 2
lr_schedule: cosine-anneal
epochs: 150
lr: 0.01
weight_decay: 1.0e-4
seed: -1
gpus: [0, 1]
port: "1234"