arch: resnet50
name: random
chkpt_file: ./model.pth
dataset: cifar10
dataset_location: /scratch/jakobj/torchdata
batch_size: 200
workers: 2
epochs: 30
lr_schedule: exponential
lr_gamma: 0.97
lr: 0.001
weight_decay: 0
optimizer: adam
multi_mag_majority_vote: True
drop_classes: []
gpus: [0]
port: 1234