arch: resnet50
name: random
chkpt_file: ./runs/simclr-nfs-1/best.pth
dataset: nfs
dataset_location: /nvmescratch/jakobj/multimag
batch_size: 64
workers: 2
epochs: 150
frozen_epochs: 20
lr_schedule: exponential
lr_gamma: 0.97
lr: 0.001
weight_decay: 0
optimizer: adam
multi_mag_majority_vote: True
gpus: [2, 3]
mode: tune