arch: resnet50
name: random
chkpt_file: ./model.pth
dataset: nfs
dataset_location: /scratch/jakobj/multimag
batch_size: 64
workers: 2
lr_schedule: exponential
epochs: 100
lr: 0.01
weight_decay: 1.0e-6
find_unused_parameters: False
seed: -1
gpus: [0, 1, 2, 3]
optimizer: "adam"
port: "1234"