arch: resnet50
name: random
dataset: nfs
dataset_location: /scratch/jakobj/multimag
batch_size: 64
workers: 2
lr_schedule: cosine-anneal
epochs: 200
lr: 1
weight_decay: 1.0e-4
seed: -1
gpus: [0, 1, 2, 3]
port: "1234"