arch: resnet50
name: nfs-1
dataset: nfs
dataset_location: /nvmescratch/jakobj/multimag
batch_size: 512
workers: 2
lr_schedule: cosine-anneal
epochs: 1000
lr: 0.001
weight_decay: 1.0e-6
tau: 1.
multiplier: 2
find_unused_parameters: True
seed: -1
gpus: [0, 1, 2, 3]
optimizer: adam
port: 1234