arch: resnet50
name: random
dataset: nfs
dataset_location: /scratch/jakobj/multimag
batch_size: 64
workers: 0
lr_schedule: cosine-anneal
epochs: 150
lr: 0.01
weight_decay: 1.0e-4
seed: -1
gpus: [2, 3]
port: "1234"