arch: resnet50
name: drop-two
dataset: nfs
dataset_location: /nvmescratch/jakobj/multimag
batch_size: 400
workers: 2
epochs: 1000
lr_schedule: cosine-anneal
lr: 1.
weight_decay: 1.0e-6
optimizer: lars
tau: 0.5
multiplier: 2
gpus: [1, 2]
# drop_classes: []
drop_classes: ["UO3AUC", "UO3SDU"] #, "U3O8AUC", "UO2SDU"]