arch: # resnet18 or resnet50, backbone model architecture
name: # run name
dataset: # cifar, dataset
dataset_location: # dataset filepath
batch_size: # int, batch size
workers: # int, dataloader worker threads
lr_schedule: # cosine-anneal or exponential, learning rate schedule
epochs: # int, num training epochs
lr: # float, learning rate
weight_decay: # float, optimizer weight decay
seed: # random seed, -1 for random
gpus: # int or list, gpu(s) to use